// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using Newtonsoft.Json;
using PlayStationSharp.Model.CommentModelJsonTypes;

namespace PlayStationSharp.Model.CommentModelJsonTypes
{
	public class UserComment
	{
		[JsonProperty("onlineId")]
		public string OnlineId { get; set; }

		[JsonProperty("realName")]
		public string RealName { get; set; }

		[JsonProperty("displayPicUrl")]
		public string DisplayPicUrl { get; set; }

		[JsonProperty("countryCode")]
		public string CountryCode { get; set; }

		[JsonProperty("commentString")]
		public string CommentString { get; set; }

		[JsonProperty("accountId")]
		public string AccountId { get; set; }

		[JsonProperty("isOfficiallyVerified")]
		public bool IsOfficiallyVerified { get; set; }

		[JsonProperty("commentId")]
		public string CommentId { get; set; }

		[JsonProperty("deleteType")]
		public string DeleteType { get; set; }

		[JsonProperty("date")]
		public string Date { get; set; }
	}

}

namespace PlayStationSharp.Model
{
	public class CommentModel
	{
		[JsonProperty("last")]
		public string Last { get; set; }

		[JsonProperty("userComments")]
		public IList<UserComment> UserComments { get; set; }

		[JsonProperty("totalCommentCount")]
		public int TotalCommentCount { get; set; }
	}
}
