// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PlayStationSharp.Model.ErrorModelJsonTypes;

namespace PlayStationSharp.Model.ErrorModelJsonTypes
{
	public class Error
	{
		[JsonProperty("code")]
		public int Code { get; set; }

		[JsonProperty("message")]
		public string Message { get; set; }
	}
}

namespace PlayStationSharp.Model
{
	public class ErrorModel
	{
		[JsonProperty("error")]
		public Error Error { get; set; }
	}

}
