// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace PlayStationSharp.Model
{
	public class SessionModel
	{
		public class NpTitleDetail2
		{

			[JsonProperty("npTitleId")]
			public string NpTitleId { get; set; }

			[JsonProperty("npTitleName")]
			public string NpTitleName { get; set; }

			[JsonProperty("npTitleIconUrl")]
			public string NpTitleIconUrl { get; set; }

			[JsonProperty("npCommunicationId")]
			public string NpCommunicationId { get; set; }

			[JsonProperty("platform")]
			public string Platform { get; set; }
		}

		public class Member
		{
			[JsonProperty("onlineId")]
			public string OnlineId { get; set; }

			[JsonProperty("platform")]
			public string Platform { get; set; }
		}

		public class Session
		{

			[JsonProperty("platform")]
			public string Platform { get; set; }

			[JsonProperty("npTitleType")]
			public string NpTitleType { get; set; }

			[JsonProperty("sessionId")]
			public string SessionId { get; set; }

			[JsonProperty("sessionMaxUser")]
			public int SessionMaxUser { get; set; }

			[JsonProperty("sessionName")]
			public string SessionName { get; set; }

			[JsonProperty("sessionCreateTimestamp")]
			public long SessionCreateTimestamp { get; set; }

			[JsonProperty("availablePlatforms")]
			public IList<string> AvailablePlatforms { get; set; }

			[JsonProperty("memberCount")]
			public int MemberCount { get; set; }

			[JsonProperty("npTitleDetail")]
			public NpTitleDetail2 NpTitleDetail { get; set; }

			[JsonProperty("members")]
			public IList<Member> Members { get; set; }
		}


		[JsonProperty("start")]
		public int Start { get; set; }

		[JsonProperty("size")]
		public int Size { get; set; }

		[JsonProperty("totalResults")]
		public int TotalResults { get; set; }

		[JsonProperty("sessions")]
		public IList<Session> Sessions { get; set; }

	}
}
