// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PlayStationSharp.Model.ThreadModelJsonTypes;

namespace PlayStationSharp.Model.ThreadModelJsonTypes
{
	public class ThreadMember
	{
		[JsonProperty("accountId")]
		public string AccountId { get; set; }

		[JsonProperty("onlineId")]
		public string OnlineId { get; set; }
	}

	public class ThreadNameDetail
	{
		[JsonProperty("status")]
		public int Status { get; set; }

		[JsonProperty("threadName")]
		public string ThreadName { get; set; }
	}

	public class ThreadThumbnailDetail
	{
		[JsonProperty("status")]
		public int Status { get; set; }
	}

	public class FavoriteDetail
	{
		[JsonProperty("favoriteFlag")]
		public bool FavoriteFlag { get; set; }
	}

	public class NotificationDetail
	{
		[JsonProperty("pushNotificationFlag")]
		public bool PushNotificationFlag { get; set; }
	}

	public class ThreadProperty
	{
		[JsonProperty("favoriteDetail")]
		public FavoriteDetail FavoriteDetail { get; set; }

		[JsonProperty("notificationDetail")]
		public NotificationDetail NotificationDetail { get; set; }

		[JsonProperty("kickoutFlag")]
		public bool KickoutFlag { get; set; }

		[JsonProperty("unreadFlag")]
		public bool UnreadFlag { get; set; }

		[JsonProperty("threadJoinDate")]
		public string ThreadJoinDate { get; set; }
	}

	public class Sender
	{
		[JsonProperty("accountId")]
		public string AccountId { get; set; }

		[JsonProperty("onlineId")]
		public string OnlineId { get; set; }
	}

	public class MessageDetail
	{
		[JsonProperty("body")]
		public string Body { get; set; }
	}

	public class LatestMessageEventDetail
	{
		[JsonProperty("eventIndex")]
		public string EventIndex { get; set; }

		[JsonProperty("postDate")]
		public string PostDate { get; set; }

		[JsonProperty("eventCategoryCode")]
		public int EventCategoryCode { get; set; }

		[JsonProperty("altEventCategoryCode")]
		public int AltEventCategoryCode { get; set; }

		[JsonProperty("sender")]
		public Sender Sender { get; set; }

		[JsonProperty("messageDetail")]
		public MessageDetail MessageDetail { get; set; }
	}

	public class NewArrivalEventDetail
	{
		[JsonProperty("newArrivalEventFlag")]
		public bool NewArrivalEventFlag { get; set; }
	}

	public class MessageEventDetail
	{
		[JsonProperty("eventIndex")]
		public string EventIndex { get; set; }

		[JsonProperty("postDate")]
		public string PostDate { get; set; }

		[JsonProperty("eventCategoryCode")]
		public int EventCategoryCode { get; set; }

		[JsonProperty("altEventCategoryCode")]
		public int AltEventCategoryCode { get; set; }

		[JsonProperty("sender")]
		public Sender Sender { get; set; }

		[JsonProperty("messageDetail")]
		public MessageDetail MessageDetail { get; set; }
	}

	public class ThreadEvent
	{

		[JsonProperty("messageEventDetail")]
		public MessageEventDetail MessageEventDetail { get; set; }
	}
}

namespace PlayStationSharp.Model
{

	public class ThreadsModel
	{
		[JsonProperty("threads")]
		public IList<ThreadModel> Threads { get; set; }

		[JsonProperty("start")]
		public int Start { get; set; }

		[JsonProperty("size")]
		public int Size { get; set; }

		[JsonProperty("totalSize")]
		public int TotalSize { get; set; }
	}

}
